export const productData = [
  {
    _id:1,
    title: '반지',
    img: 'images/image1.jpg',
    price: 1000,
    category: '',
    discount: 0,
  },
  {
    _id:2,
    title: '하트 귀걸이',
    img: 'images/image2.jpg',
    price: 1000,
    category: 'top',
    discount: 5,
  },
  {
    _id:3,
    title: '14k 5ea',
    img: 'images/image3.jpg',
    price: 5000,
    category: '',
    discount: 0,
  },
  {
    _id:4,
    title: '핑크골드 링 목걸이',
    img: 'images/image4.jpg',
    price: 10000,
    category: '',
    discount: 0,
  },
  {
    _id:5,
    title: '핑크골드 반지1',
    img: 'images/image5.jpg',
    price: 15000,
    category: '',
    discount: 0,
  },
  {
    _id:6,
    title: '핑크골드 목걸이1',
    img: 'images/image6.jpg',
    price: 5000,
    category: '',
    discount: 5,
  },
  {
    _id:7,
    title: '핀1',
    img: 'images/image7.jpg',
    price: 6000,
    category: '',
    discount: 0,
  },
  {
    _id:8,
    title: '핀2',
    img: 'images/image8.jpg',
    price: 6000,
    category: '',
    discount: 5,
  },
  {
    _id:9,
    title: '납작 목걸이',
    img: 'images/image9.jpg',
    price: 10000,
    category: '',
    discount: 0,
  },
  {
    _id:10,
    title: '핀3',
    img: 'images/image10.jpg',
    price: 0,
    category: '',
    discount: 0,
  },

]